export const type = {
    // Syn
    CREATE_INGREDIENT:       'CREATE_INGREDIENT',
    FILL_INGREDIENTS:        'FILL_INGREDIENTS',
    // Asyn
    CREATE_INGREDIENT_ASYNC: 'CREATE_INGREDIENT_ASYNC',
    FETCH_INGREDIENTS_ASYNC: 'FETCH_INGREDIENTS_ASYNC',
};
