export const type = {
    // Syn
    ADD_BURGER_INTENT:    'ADD_BURGER_INTENT',
    REMOVE_BURGER_INTENT: 'REMOVE_BURGER_INTENT',

    ADD_AVAILABLE_INTENT:    'ADD_AVAILABLE_INTENT',
    REMOVE_AVAILABLE_INTENT: 'REMOVE_AVAILABLE_INTENT',

    FILL_BURGER_INGREDIENTS: 'FILL_BURGER_INGREDIENTS',
    // Asyn
    REMOVE_INTENT_ASYNC:     'REMOVE_INTENT_ASYNC',
    ADD_INTENT_ASYNC:        'ADD_INTENT_ASYNC',

    FETCH_BURGER_INGREDIENTS_ASYNC: 'FETCH_BURGER_INGREDIENTS_ASYNC',

};
